// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blog.proto

package org.banulp;

public final class Blog {
  private Blog() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_banulp_CreateBlogPostRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_banulp_CreateBlogPostRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_banulp_GetBlogPostRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_banulp_GetBlogPostRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_banulp_ListBlogPostsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_banulp_ListBlogPostsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_banulp_ListBlogPostsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_banulp_ListBlogPostsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_banulp_UpdateBlogPostRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_banulp_UpdateBlogPostRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_banulp_DeleteBlogPostRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_banulp_DeleteBlogPostRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_banulp_BlogPost_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_banulp_BlogPost_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\nblog.proto\022\norg.banulp\032\033google/protobu" +
      "f/empty.proto\"7\n\025CreateBlogPostRequest\022\r" +
      "\n\005title\030\001 \001(\t\022\017\n\007content\030\002 \001(\t\" \n\022GetBlo" +
      "gPostRequest\022\n\n\002id\030\001 \001(\005\"*\n\024ListBlogPost" +
      "sRequest\022\022\n\ndescending\030\001 \001(\010\"<\n\025ListBlog" +
      "PostsResponse\022#\n\005blogs\030\001 \003(\0132\024.org.banul" +
      "p.BlogPost\"C\n\025UpdateBlogPostRequest\022\n\n\002i" +
      "d\030\001 \001(\005\022\r\n\005title\030\002 \001(\t\022\017\n\007content\030\003 \001(\t\"" +
      "#\n\025DeleteBlogPostRequest\022\n\n\002id\030\001 \001(\005\"]\n\010" +
      "BlogPost\022\n\n\002id\030\001 \001(\005\022\r\n\005title\030\002 \001(\t\022\017\n\007c",
      "ontent\030\003 \001(\t\022\021\n\tcreatedAt\030\004 \001(\003\022\022\n\nmodif" +
      "iedAt\030\005 \001(\0032\225\003\n\013BlogService\022K\n\016CreateBlo" +
      "gPost\022!.org.banulp.CreateBlogPostRequest" +
      "\032\024.org.banulp.BlogPost\"\000\022E\n\013GetBlogPost\022" +
      "\036.org.banulp.GetBlogPostRequest\032\024.org.ba" +
      "nulp.BlogPost\"\000\022V\n\rListBlogPosts\022 .org.b" +
      "anulp.ListBlogPostsRequest\032!.org.banulp." +
      "ListBlogPostsResponse\"\000\022K\n\016UpdateBlogPos" +
      "t\022!.org.banulp.UpdateBlogPostRequest\032\024.o" +
      "rg.banulp.BlogPost\"\000\022M\n\016DeleteBlogPost\022!",
      ".org.banulp.DeleteBlogPostRequest\032\026.goog" +
      "le.protobuf.Empty\"\000B\016\n\norg.banulpP\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_org_banulp_CreateBlogPostRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_banulp_CreateBlogPostRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_banulp_CreateBlogPostRequest_descriptor,
        new String[] { "Title", "Content", });
    internal_static_org_banulp_GetBlogPostRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_banulp_GetBlogPostRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_banulp_GetBlogPostRequest_descriptor,
        new String[] { "Id", });
    internal_static_org_banulp_ListBlogPostsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_banulp_ListBlogPostsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_banulp_ListBlogPostsRequest_descriptor,
        new String[] { "Descending", });
    internal_static_org_banulp_ListBlogPostsResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_org_banulp_ListBlogPostsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_banulp_ListBlogPostsResponse_descriptor,
        new String[] { "Blogs", });
    internal_static_org_banulp_UpdateBlogPostRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_org_banulp_UpdateBlogPostRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_banulp_UpdateBlogPostRequest_descriptor,
        new String[] { "Id", "Title", "Content", });
    internal_static_org_banulp_DeleteBlogPostRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_org_banulp_DeleteBlogPostRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_banulp_DeleteBlogPostRequest_descriptor,
        new String[] { "Id", });
    internal_static_org_banulp_BlogPost_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_org_banulp_BlogPost_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_banulp_BlogPost_descriptor,
        new String[] { "Id", "Title", "Content", "CreatedAt", "ModifiedAt", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
