// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blog.proto

package org.banulp;

public interface BlogPostOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.banulp.BlogPost)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string title = 2;</code>
   */
  String getTitle();
  /**
   * <code>string title = 2;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string content = 3;</code>
   */
  String getContent();
  /**
   * <code>string content = 3;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>int64 createdAt = 4;</code>
   */
  long getCreatedAt();

  /**
   * <code>int64 modifiedAt = 5;</code>
   */
  long getModifiedAt();
}
