// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blog.proto

package org.banulp;

public interface CreateBlogPostRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.banulp.CreateBlogPostRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string title = 1;</code>
   */
  String getTitle();
  /**
   * <code>string title = 1;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string content = 2;</code>
   */
  String getContent();
  /**
   * <code>string content = 2;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
