// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blog.proto

package org.banulp;

public interface GetBlogPostRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.banulp.GetBlogPostRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
