// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blog.proto

package org.banulp;

public interface ListBlogPostsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.banulp.ListBlogPostsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .org.banulp.BlogPost blogs = 1;</code>
   */
  java.util.List<BlogPost>
      getBlogsList();
  /**
   * <code>repeated .org.banulp.BlogPost blogs = 1;</code>
   */
  BlogPost getBlogs(int index);
  /**
   * <code>repeated .org.banulp.BlogPost blogs = 1;</code>
   */
  int getBlogsCount();
  /**
   * <code>repeated .org.banulp.BlogPost blogs = 1;</code>
   */
  java.util.List<? extends BlogPostOrBuilder>
      getBlogsOrBuilderList();
  /**
   * <code>repeated .org.banulp.BlogPost blogs = 1;</code>
   */
  BlogPostOrBuilder getBlogsOrBuilder(
      int index);
}
