// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blog.proto

package org.banulp;

public interface ListBlogPostsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.banulp.ListBlogPostsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool descending = 1;</code>
   */
  boolean getDescending();
}
