// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blog.proto

package org.banulp;

/**
 * Protobuf type {@code org.banulp.ListBlogPostsResponse}
 */
public  final class ListBlogPostsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.banulp.ListBlogPostsResponse)
    ListBlogPostsResponseOrBuilder {
  // Use ListBlogPostsResponse.newBuilder() to construct.
  private ListBlogPostsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListBlogPostsResponse() {
    blogs_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ListBlogPostsResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              blogs_ = new java.util.ArrayList<BlogPost>();
              mutable_bitField0_ |= 0x00000001;
            }
            blogs_.add(
                input.readMessage(BlogPost.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        blogs_ = java.util.Collections.unmodifiableList(blogs_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Blog.internal_static_org_banulp_ListBlogPostsResponse_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Blog.internal_static_org_banulp_ListBlogPostsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ListBlogPostsResponse.class, Builder.class);
  }

  public static final int BLOGS_FIELD_NUMBER = 1;
  private java.util.List<BlogPost> blogs_;
  /**
   * <code>repeated .org.banulp.BlogPost blogs = 1;</code>
   */
  public java.util.List<BlogPost> getBlogsList() {
    return blogs_;
  }
  /**
   * <code>repeated .org.banulp.BlogPost blogs = 1;</code>
   */
  public java.util.List<? extends BlogPostOrBuilder>
      getBlogsOrBuilderList() {
    return blogs_;
  }
  /**
   * <code>repeated .org.banulp.BlogPost blogs = 1;</code>
   */
  public int getBlogsCount() {
    return blogs_.size();
  }
  /**
   * <code>repeated .org.banulp.BlogPost blogs = 1;</code>
   */
  public BlogPost getBlogs(int index) {
    return blogs_.get(index);
  }
  /**
   * <code>repeated .org.banulp.BlogPost blogs = 1;</code>
   */
  public BlogPostOrBuilder getBlogsOrBuilder(
      int index) {
    return blogs_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < blogs_.size(); i++) {
      output.writeMessage(1, blogs_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < blogs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, blogs_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ListBlogPostsResponse)) {
      return super.equals(obj);
    }
    ListBlogPostsResponse other = (ListBlogPostsResponse) obj;

    boolean result = true;
    result = result && getBlogsList()
        .equals(other.getBlogsList());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getBlogsCount() > 0) {
      hash = (37 * hash) + BLOGS_FIELD_NUMBER;
      hash = (53 * hash) + getBlogsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ListBlogPostsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ListBlogPostsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ListBlogPostsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ListBlogPostsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ListBlogPostsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ListBlogPostsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ListBlogPostsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ListBlogPostsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ListBlogPostsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ListBlogPostsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ListBlogPostsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ListBlogPostsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ListBlogPostsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.banulp.ListBlogPostsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.banulp.ListBlogPostsResponse)
      ListBlogPostsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Blog.internal_static_org_banulp_ListBlogPostsResponse_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Blog.internal_static_org_banulp_ListBlogPostsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ListBlogPostsResponse.class, Builder.class);
    }

    // Construct using org.banulp.ListBlogPostsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBlogsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (blogsBuilder_ == null) {
        blogs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        blogsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Blog.internal_static_org_banulp_ListBlogPostsResponse_descriptor;
    }

    public ListBlogPostsResponse getDefaultInstanceForType() {
      return ListBlogPostsResponse.getDefaultInstance();
    }

    public ListBlogPostsResponse build() {
      ListBlogPostsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public ListBlogPostsResponse buildPartial() {
      ListBlogPostsResponse result = new ListBlogPostsResponse(this);
      int from_bitField0_ = bitField0_;
      if (blogsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          blogs_ = java.util.Collections.unmodifiableList(blogs_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.blogs_ = blogs_;
      } else {
        result.blogs_ = blogsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ListBlogPostsResponse) {
        return mergeFrom((ListBlogPostsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ListBlogPostsResponse other) {
      if (other == ListBlogPostsResponse.getDefaultInstance()) return this;
      if (blogsBuilder_ == null) {
        if (!other.blogs_.isEmpty()) {
          if (blogs_.isEmpty()) {
            blogs_ = other.blogs_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureBlogsIsMutable();
            blogs_.addAll(other.blogs_);
          }
          onChanged();
        }
      } else {
        if (!other.blogs_.isEmpty()) {
          if (blogsBuilder_.isEmpty()) {
            blogsBuilder_.dispose();
            blogsBuilder_ = null;
            blogs_ = other.blogs_;
            bitField0_ = (bitField0_ & ~0x00000001);
            blogsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBlogsFieldBuilder() : null;
          } else {
            blogsBuilder_.addAllMessages(other.blogs_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ListBlogPostsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ListBlogPostsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<BlogPost> blogs_ =
      java.util.Collections.emptyList();
    private void ensureBlogsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        blogs_ = new java.util.ArrayList<BlogPost>(blogs_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        BlogPost, BlogPost.Builder, BlogPostOrBuilder> blogsBuilder_;

    /**
     * <code>repeated .org.banulp.BlogPost blogs = 1;</code>
     */
    public java.util.List<BlogPost> getBlogsList() {
      if (blogsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(blogs_);
      } else {
        return blogsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .org.banulp.BlogPost blogs = 1;</code>
     */
    public int getBlogsCount() {
      if (blogsBuilder_ == null) {
        return blogs_.size();
      } else {
        return blogsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .org.banulp.BlogPost blogs = 1;</code>
     */
    public BlogPost getBlogs(int index) {
      if (blogsBuilder_ == null) {
        return blogs_.get(index);
      } else {
        return blogsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .org.banulp.BlogPost blogs = 1;</code>
     */
    public Builder setBlogs(
        int index, BlogPost value) {
      if (blogsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBlogsIsMutable();
        blogs_.set(index, value);
        onChanged();
      } else {
        blogsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.banulp.BlogPost blogs = 1;</code>
     */
    public Builder setBlogs(
        int index, BlogPost.Builder builderForValue) {
      if (blogsBuilder_ == null) {
        ensureBlogsIsMutable();
        blogs_.set(index, builderForValue.build());
        onChanged();
      } else {
        blogsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.banulp.BlogPost blogs = 1;</code>
     */
    public Builder addBlogs(BlogPost value) {
      if (blogsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBlogsIsMutable();
        blogs_.add(value);
        onChanged();
      } else {
        blogsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .org.banulp.BlogPost blogs = 1;</code>
     */
    public Builder addBlogs(
        int index, BlogPost value) {
      if (blogsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBlogsIsMutable();
        blogs_.add(index, value);
        onChanged();
      } else {
        blogsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.banulp.BlogPost blogs = 1;</code>
     */
    public Builder addBlogs(
        BlogPost.Builder builderForValue) {
      if (blogsBuilder_ == null) {
        ensureBlogsIsMutable();
        blogs_.add(builderForValue.build());
        onChanged();
      } else {
        blogsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.banulp.BlogPost blogs = 1;</code>
     */
    public Builder addBlogs(
        int index, BlogPost.Builder builderForValue) {
      if (blogsBuilder_ == null) {
        ensureBlogsIsMutable();
        blogs_.add(index, builderForValue.build());
        onChanged();
      } else {
        blogsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.banulp.BlogPost blogs = 1;</code>
     */
    public Builder addAllBlogs(
        Iterable<? extends BlogPost> values) {
      if (blogsBuilder_ == null) {
        ensureBlogsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, blogs_);
        onChanged();
      } else {
        blogsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .org.banulp.BlogPost blogs = 1;</code>
     */
    public Builder clearBlogs() {
      if (blogsBuilder_ == null) {
        blogs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        blogsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .org.banulp.BlogPost blogs = 1;</code>
     */
    public Builder removeBlogs(int index) {
      if (blogsBuilder_ == null) {
        ensureBlogsIsMutable();
        blogs_.remove(index);
        onChanged();
      } else {
        blogsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .org.banulp.BlogPost blogs = 1;</code>
     */
    public BlogPost.Builder getBlogsBuilder(
        int index) {
      return getBlogsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .org.banulp.BlogPost blogs = 1;</code>
     */
    public BlogPostOrBuilder getBlogsOrBuilder(
        int index) {
      if (blogsBuilder_ == null) {
        return blogs_.get(index);  } else {
        return blogsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .org.banulp.BlogPost blogs = 1;</code>
     */
    public java.util.List<? extends BlogPostOrBuilder>
         getBlogsOrBuilderList() {
      if (blogsBuilder_ != null) {
        return blogsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(blogs_);
      }
    }
    /**
     * <code>repeated .org.banulp.BlogPost blogs = 1;</code>
     */
    public BlogPost.Builder addBlogsBuilder() {
      return getBlogsFieldBuilder().addBuilder(
          BlogPost.getDefaultInstance());
    }
    /**
     * <code>repeated .org.banulp.BlogPost blogs = 1;</code>
     */
    public BlogPost.Builder addBlogsBuilder(
        int index) {
      return getBlogsFieldBuilder().addBuilder(
          index, BlogPost.getDefaultInstance());
    }
    /**
     * <code>repeated .org.banulp.BlogPost blogs = 1;</code>
     */
    public java.util.List<BlogPost.Builder>
         getBlogsBuilderList() {
      return getBlogsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        BlogPost, BlogPost.Builder, BlogPostOrBuilder>
        getBlogsFieldBuilder() {
      if (blogsBuilder_ == null) {
        blogsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            BlogPost, BlogPost.Builder, BlogPostOrBuilder>(
                blogs_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        blogs_ = null;
      }
      return blogsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:org.banulp.ListBlogPostsResponse)
  }

  // @@protoc_insertion_point(class_scope:org.banulp.ListBlogPostsResponse)
  private static final ListBlogPostsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ListBlogPostsResponse();
  }

  public static ListBlogPostsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListBlogPostsResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListBlogPostsResponse>() {
    public ListBlogPostsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ListBlogPostsResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ListBlogPostsResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ListBlogPostsResponse> getParserForType() {
    return PARSER;
  }

  public ListBlogPostsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

